version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3070:3000"
    environment:
      - RAILS_ENV=production
      - HOSTNAME=sendpostform.zaidhuda.com
      - SECRET_KEY_BASE=secret
      - SMTP_API_KEY=secret
      - SMTP_DOMAIN=secret
